export const QUERY_KEYS = {
  INFINITE: {},
  PUBLIC: {
    SK: ["public", "sk"],
  },
  DASHBOARD: {
    STATUS_COUNT: ["dashboard", "status-count"],
    MY_SK_LIST: ["dashboard", "my-sk-list"],
  },
  AUTH: {
    ME: ["auth", "me"],
  },
  SK: {
    KEMATIAN: ["sk", "kematian"],
    KEMATIAN_DETAIL: ["sk", "kematian", "detail"],
    TIDAK_MAMPU: ["sk", "tidak-mampu"],
    TIDAK_MAMPU_DETAIL: ["sk", "tidak-mampu", "detail"],
    DISPENSASI: ["sk", "dispensasi"],
    DISPENSASI_DETAIL: ["sk", "dispensasi", "detail"],
    BEDA_NAMA: ["sk", "beda-nama"],
    BEDA_NAMA_DETAIL: ["sk", "beda-nama", "detail"],
    DOMISILI: ["sk", "domisili"],
    DOMISILI_DETAIL: ["sk", "domisili", "detail"],
    KEHILANGAN: ["sk", "kehilangan"],
    KEHILANGAN_DETAIL: ["sk", "kehilangan", "detail"],
    KELAHIRAN: ["sk", "kelahiran"],
    KELAHIRAN_DETAIL: ["sk", "kelahiran", "detail"],
    USAHA: ["sk", "usaha"],
    USAHA_DETAIL: ["sk", "usaha", "detail"],
    KTP_SEMENTARA: ["sk", "ktp-sementara"],
    KTP_SEMENTARA_DETAIL: ["sk", "ktp-sementara", "detail"],
    LIST: ["sk", "list"],
  },
  ADMIN: {
    ROLES: ["admin", "roles"],
    ROLE_DETAIL: ["admin", "role", "detail"],
    PERMISSIONS: ["admin", "permissions"],
    USERS: ["admin", "users"],
    USER_DETAIL: ["admin", "user", "detail"],
    SK_APPROVER_SETTINGS: ["admin", "sk-approver-settings"],
  },
} as const;
